import axios from 'axios'
import md5 from 'md5'

const publicKey = process.env.REACT_APP_MARVEL_PUBLIC_KEY //publicKey generated by Marvel website
const privateKey = process.env.REACT_APP_MARVEL_PRIVATE_KEY //privateKey generated by Marvel website

const ts = Number(new Date()) // timestamp is required on params for request in marvel api

const hash = md5(ts + privateKey + publicKey) // hash is required on params for request in marvel api

const marvelApi = axios.create({
  baseURL: "http://gateway.marvel.com/v1/public",
  params: {
    ts: ts,
    apikey: publicKey,
    hash: hash
  }
})

export default marvelApi